### ISSUE TITLE
install cnvkit in galaxy tool shed

### ISSUE THREAD

**Issue by Dare-IC** [etal/cnvkit#299]
Why do I get this warning when installing CNVkit from galaxy tool shed: Repository installation is not possible due to an invalid Galaxy URL: <b> None </ B>. You may need to enable third-party cookies in your browser.

But I've started third-party cookies in my browser....Why this problem occurs, please tell me if you know it, thank you.

**Comment by etal** [comment]
Thanks for letting me know. It looks like the Galaxy tool wrapper requirements may have changed and I'll need to update the wrapper for CNVkit.

I think you can still install CNVkit separately with `conda`, see the README file in this repo.

**Comment by Dare-IC** [comment]
Thank you for your reply. I am looking forward to using CNVkit on Galaxy Tools.

but,in conda, this error occurred when using the batch directive:
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2

Where is my problem? Looking forward to your reply.

**Comment by etal** [comment]
It looks like a problem that was fixed at least in the development version of CNVkit, which you can install from GitHub. Or, you can downgrade numpy to the previous version 1.12. (Numpy used to allow this kind of indexing, but doesn't as of 1.13.)

**Comment by Dare-IC** [comment]
Thank you for you reply.

l still have a question in DNAnexus , When I used the wgs of cnvkit, I got an error:  failed to complete because of an error of type "AppInternalError". The error was: "CalledProcessError: Command 'dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.9.1 cnvkit.py batch -m wgs --output-reference cnv-reference.cnn -n Galaxy38-[Map_with_BWA-MEM_on_data_34_and_data_33_(mapped_reads_in_BAM_format)].bam -f human_g1k_v37.fasta --annotate refFlat.txt -p 8 -y' returned non-zero exit status 2"。

How to solve this error? 

Look forward to your reply, thanks again.

**Comment by etal** [comment]
Can you look in the job log for another traceback above the one from dx-docker? The earlier log message should show the underlying error.

Another user reported that the DNAnexus app could crash if no test/tumor sample BAM files were provided as input. I thought I'd fixed in in the most recent version of the app. In any case, if the error message suggests that might be the issue (uninitialized variable, something like that), then try providing one or more test files as input alongside your existing inputs.

**Comment by Dare-IC** [comment]
Thank you for your answer, l used a low version of cnvkit, but there was a problem: [Errno 2] No such file or directory: ' batch '
looking forward to your reply, thank you again.

**Comment by etal** [comment]
Can you try the most recent version of the DNAnexus app, then?

**Comment by Dare-IC** [comment]
![sample_1-1](https://user-images.githubusercontent.com/32573150/34870663-c2af1b44-f7c5-11e7-8bb1-1fe26cc57026.png)

![sample_1](https://user-images.githubusercontent.com/32573150/34870412-f0853748-f7c4-11e7-84d8-b40138063b71.png)

Thank you for your answer, I've run cnvkit successfully,However,during the wgs analysis, I found that the results of the analysis of cnvkit which scatter and heatmap png images output is confusing, and this is why?

I will send my results to you, would like to ask you to answer it, thank you again.

**Comment by etal** [comment]
There are a few issues:

1. See #169 -- the results you see in the plots include all of the alternative contigs in your reference genome sequence (FASTA file). These are displayed as separate chromosomes, but they're not very useful. It would probably be reasonable to [drop the alternative chromosomes](https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use), or use a reference FASTA that doesn't have them, throughout your analysis pipeline.
2. There are a lot of bins with zero read depth, and quite a few with unusually high read depth. Your WGS analysis might need a much larger bin size -- what was your average read depth? Was the input sample truly WGS, or could it have been an exome by mistake? 
3. The segments in your scatter plot don't seem to correspond to the ones in your heatmap -- the heatmap seems to have dropped a lot of regions.

Problems 2 and 3 might be resolved to some extent by using a pooled or at least paired reference. Reference-free CNV calling is inevitably noisier, and doesn't have the necessary information to skip or down-weight problematic genomic regions.

If your intent is to analyze a germline WGS sample on DNAnexus, without a matched control sample, you might consider using the CLAMMS app instead. In either case, a pool of control samples will significantly improve the results.

**Comment by Dare-IC** [comment]
Thank you for your reply.

1. we are indeed WGS data.
2. but our WGS data comes from Single-Cell Whole-Genome Amplification and Sequencing. 
3. we sequenced a total of 6G raw data, pair-end

Would like to ask you any better comments on the changes? If yes, please tell me, thank you!

wgs for the bin, how to amend the bin value? How much to change? For wgs, probably how many bin more appropriate?

**Comment by etal** [comment]
The appropriate bin size is related to the sequencing coverage depth, and you can quickly estimate it from a sample (or set of samples) with the `autobin` command. If the number it gives you is similar to the bin size that appeared in the log messages of the `batch` command earlier, try multiplying the value by 10 and specifying that to another run of `batch` via the option `--target-avg-size`.

**Comment by Dare-IC** [comment]
Thank you for your repley.

1.When I use autobin: cnvkit.py autobin sample.bam -m wgs -b 20000 --annotate refFlat.txt. 
This problem occurred:  RuntimeError: Sequencing method 'wgs' requires accessible regions (-g).

2.when I use:
cnvkit.py batch sample.bam -n control.bam \
-m wgs -f GRCh38.fna --annotate hg38ncbi.bed --target-avg-size
Appeared: cnvkit.py batch: error: argument --target-avg-size: expected one argument

3.When I was replaced by -g ACCESS in the back, there: I0Error: [Error 2] No such file or directroy: 'ACCESS'

4.This can be set in wgs bin 15kb? Is there any problem with my input yet? Please give me guidance, thank you!

**Comment by etal** [comment]
1. The accessible regions BED file comes from the ``access`` command, calculated using the reference genome sequence (FASTA). An example for UCSC hg19 is included in the CNVkit repo under ``data/``.
2. You should specify a number after ``--target-bin-size`` (the desired bin size, in genomic bases, e.g. ``15000``).
3. Use a filename there.

**Comment by Dare-IC** [comment]
Hello, very sorry to bother you again, before you approach gave me great help, thanks again, recently, when I was in the use of software, want to use a large bin value, don't know how big can bin to?Is 2000k ok？

Looking forward to hearing from you.

**Comment by etal** [comment]
Yes, CNVkit will accept essentially any bin size. Up to 1 or 2 million bases seems reasonable for very low coverage WGS. You can use the `autobin` to quickly estimate the appropriate bin size for you using a representative BAM file from one of the samples you intend to process.
